### PR TITLE
Fix jscs errors

### LINKED ISSUE #412: TestRTC - Fix JSCS errors
Note: Remove exclude filter in Gruntfile.js for JSCS to see the errors in full glory ;)

Created from #402.

### PR DESCRIPTION
**Pull request by KaptenJansson**
Fixes #412.

### CODE REVIEW

File: samples/web/content/testrtc/js/main.js [hunk 1]
```diff
@@ -418,23 +424,21 @@ function setTimeoutWithProgressBar(timeoutCallback, timeoutMs) {
 }
 
 // Parse URL parameters and configure test filters.
-{
```
Comment (andresusanopinto) [inline samples/web/content/testrtc/js/main.js]: Can't we keep the scope?

File: samples/web/content/testrtc/js/mictest.js [hunk 2]
```diff
@@ -137,11 +137,12 @@ MicTest.prototype = {
     // Check input audio level.
     if (db < this.lowVolumeThreshold) {
       // Use Math.round to display up to two decimal places.
-      reportError('Audio input level = ' + Math.round(db * 1000) / 1000 + ' db' +
-                  'Microphone input level is low, increase input volume or' +
-                  'move closer to the microphone.');
+      reportError('Audio input level = ' + Math.round(db * 1000) / 1000 +
+                  ' db' + 'Microphone input level is low, increase input ' +
```
Comment (andresusanopinto) [inline samples/web/content/testrtc/js/mictest.js]: ' db. Microphone...'

File: samples/web/content/testrtc/js/camtest.js [hunk 3]
```diff
@@ -7,26 +7,6 @@
  */
 'use strict';
 
-// Test spec
```
Comment (andresusanopinto) [inline samples/web/content/testrtc/js/camtest.js]: I am fine with removing it. Since at some moment this comment will not match the test anymore.

File: samples/web/content/testrtc/js/main.js (hunk 1 above)
Comment (KaptenJansson) [inline samples/web/content/testrtc/js/main.js]: Block scope does not exist in javascript hence this is does not do anything.

File: samples/web/content/testrtc/js/camtest.js (hunk 3 above)
Comment (KaptenJansson) [inline samples/web/content/testrtc/js/camtest.js]: It was the initial plan for the test, now it's deprecated ;)

File: samples/web/content/testrtc/js/main.js (hunk 1 above)
Comment (andresusanopinto) [inline samples/web/content/testrtc/js/main.js]: That is indeed true! My mistake.

Can you have a proper parserUrlParameters function? Instead of var parseUrlParameters = function ?

Comment (KaptenJansson) [inline samples/web/content/testrtc/js/main.js]: Done
